name: Notificacion NTFY

on:
  push:
    branches:
      - main

jobs:
  enviar-notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar Hola Mundo
        run: node app.js

      - name: Enviar notificacion a NTFY
        run: |
          curl \
            -H "Title: Practica Integracion Continua" \
            -H "Priority: default" \
            -d "Nuevo push realizado por ${{ github.actor }} en ${{ github.repository }}" \
            https://ntfy.sh/devops-itla
